query GetCarBrands {
  carBrands {
    id
    name
  }
}

mutation AddCarBrand($name: String!) {
  createCarBrand(name: $name) {
    id
    name
  }
}

mutation EditCarBrand($id: ID!, $name: String!) {
  editCarBrand(id: $id, name: $name) {
    id
    name
  }
}

mutation DeleteCarBrand($id: ID!) {
  deleteCarBrand(id: $id) {
    id
  }
}
