query GetModels($brandId: ID!) {
  carModels(brandId: $brandId) {
      id
      name
      brand {
        id
        name
      }
    }
}

mutation DeleteCarModel($id: ID!) {
  deleteCarModel(id: $id)
}

mutation CreateCarModel($brandId: ID!, $name: String!) {
  createCarModel(brandId: $brandId, name: $name){
    id
    name
    brand {
      id
      name
    }
  }
}

mutation EditCarModel($data: CarModelData!) {
  editCarModel(data: $data){
    id
    name
    brand {
      id
      name
    }
  }
}