query CarModifications($modelId: ID!) {
  carModifications(modelId: $modelId) {
    id
    name
    coupe
    weight
    horsePower
  }
}

mutation DeleteCarModification($id: ID!) {
  deleteCarModification(id: $id)
}

mutation CreateCarModification($modelId: ID!, $name: String!) {
  createCarModification(modelId: $modelId, name: $name){
    id
    name
    coupe
    weight
    horsePower
    model {
      id
      name
    }
    
}