import type { Metadata } from 'next'
import QueryProvider from '@/store/QueryClientProvider'
import './globals.css'


export const metadata: Metadata = {
  title: 'Form Task',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
      <QueryProvider>
        {children}
      </QueryProvider>
      </body>
    </html>
  )
}
